#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>, Ulf Hermann <ulf_hermann@gmx.net>
# License: GPL

# When this script is ready, you can run
# ocs-iso -g en_US.UTF-8 -k NONE -s -m ./custom-ocs
# to create the iso file for CD/DVD. or
# ocs-live-dev -g en_US.UTF-8 -k NONE -s -c -m ./custom-ocs
# to create the zip file for USB flash drive.

# Begin of the scripts:
# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# load the setting for clonezilla live.
[ -e /etc/ocs/ocs-live.conf ] && . /etc/ocs/ocs-live.conf

# functions

choose_mode() {
  local TMP
  TMP="$(mktemp /tmp/ocssaverestore.XXXXXX)"

  echo "Choose the mode for ocs-sr"
  ASK_OCS_SR_TYPE=1
  while [ "$ASK_OCS_SR_TYPE" -ne 0 ]; do
    $DIA --backtitle "$msg_nchc_free_software_labs" --title  \
    "Clonezilla: $msg_choose_mode" --menu "$msg_clonezilla_is_free_and_no_warranty\n$msg_overwrite_data_on_disk_when_restoring\n$msg_hint_multiple_choice_select_by_space\n$msg_choose_mode:" \
    0 0 0 \
    "restore" "restore image to local disks, creating new partition table" \
    "save" "save local disk as image" \
    "proportional" "restore image to local disks, using original partition table" \
    "server" "restore image to remote computers" \
    "shell" "enter shell" \
    2> $TMP
    ocs_sr_type="$(cat $TMP)"
    if [ -z "$ocs_sr_type" ]; then
      ASK_OCS_SR_TYPE=1
    else
      ASK_OCS_SR_TYPE=0
    fi
  done
  [ -f "$TMP" ] && rm -f $TMP
  [ -z "$ocs_sr_type" ] && echo "You must specify the action! Program terminated!!!" && exit 1
}

prepare() {
  # set the flag to show color output
  BOOTUP=color
  # some parameters for color output.
  [ -z "$SETCOLOR_SUCCESS" ] && SETCOLOR_SUCCESS="echo -en \\033[1;32m"
  [ -z "$SETCOLOR_FAILURE" ] && SETCOLOR_FAILURE="echo -en \\033[1;31m"
  [ -z "$SETCOLOR_WARNING" ] && SETCOLOR_WARNING="echo -en \\033[1;33m"
  [ -z "$SETCOLOR_NORMAL"  ] && SETCOLOR_NORMAL="echo -en \\033[0;39m"
  
  # Clean /etc/motd to avoid confusion.
  echo -n "" > /etc/motd

  # Decide where is the $LIVE_MEDIA
  get_live_media_mnt_point

  # Try to force to remount /$LIVE_MEDIA as rw, since it's rw device, like USB disk, we can try to save clonezilla image.
  mount -o remount,rw /$LIVE_MEDIA
  
  ask_language_if_supported_with_bterm
  [ -z "$ocs_lang" ] && ocs_lang=en
  ask_and_load_lang_set $ocs_lang

  DIA="whiptail"
}

##################
###### MAIN ######
##################

prepare
choose_mode

mount `mount | grep $LIVE_MEDIA | awk '{print $1}' | sed -e 's/\(dev\/sd.\)1/\12/'` /mnt
mount -o bind /mnt/home/partimag /home/partimag

case "$ocs_sr_type" in
  "save")
    ocs-sr -p true -b -sc -g auto -e1 auto -e2 -r -j2 -q2 savedisk "ask_user" "ask_user"
    ;;
  "restore")
    # To get $target_hd
    ocs_mode_prompt="1-2-mdisks"
    get_target_hd_name_from_local_machine "$msg_choose_the_disks_to_restore \n$msg_linux_disk_naming $msg_press_space_to_mark_selection" checklist
    good_disks=""
    for disk in $target_hd; do
      if /mnt/root/partition /dev/$disk; then
	good_disks="$good_disks $disk";
      else
	echo "$disk is unsuitable. Ignoring"
	sleep 10
      fi
    done
    ocs-restore-mdisks -b -p "-c -p true -k -g auto -e1 auto -e2 -r -j2" "ask_user" "$good_disks"
    ;;
  "proportional")
    # To get $target_hd
    ocs_mode_prompt="1-2-mdisks"
    get_target_hd_name_from_local_machine "$msg_choose_the_disks_to_restore \n$msg_linux_disk_naming $msg_press_space_to_mark_selection" checklist
    ocs-restore-mdisks -b -p "-c -p true -k1 -g auto -e1 auto -e2 -r -j2" "ask_user" "$target_hd"
    ;;
  "server")
    /mnt/drblmount
    ;;
  "shell")
    /bin/bash
    ;;
  *)
    echo "invalid choice"
    ;;
esac

umount /home/partimag
umount /mnt

exit 1


