#!/bin/sh

mount -o rbind /dev /mnt/dev
mount -t proc none /mnt/proc
mount -t sysfs none /mnt/sys
mount -t overlayfs -o upperdir=/mnt/lib/modules,lowerdir=/lib/modules overlayfs /mnt/lib/modules

chroot /mnt sh -c "/usr/local/sbin/startdrbl; /bin/bash; /usr/local/sbin/stopdrbl"

cat /proc/mounts | grep '/mnt/' | awk '{print $2}' | sort -r | xargs umount