#!/bin/sh

clients=$1
image=$2

#/opt/drbl/sbin/drbl-ocs -b -g auto -e1 auto -e2 -x -r -j2 -k -p reboot --clients-to-wait 1 -l en_US.UTF-8 -o0 startparts multicast_restore 2012-11-16-17-img sda2 sda3
#/opt/drbl/sbin/drbl-ocs -b -g auto -e1 auto -e2 -x -r -j2 -k -p reboot --clients-to-wait 1 --max-time-to-wait 300 -l en_US.UTF-8 -o0 startdisk multicast_restore 2012-12-01-disk-img sda

/opt/drbl/sbin/drbl-ocs -b -g auto -e1 auto -e2 -x -r -j2 -k -p reboot --clients-to-wait $clients --max-time-to-wait 300 -l en_US.UTF-8 -o0 startdisk multicast_restore $image sda
